# Generated by Django 2.0.1 on 2018-09-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('writer', models.CharField(max_length=16)),
                ('publishing', models.CharField(max_length=32)),
            ],
        ),
    ]
