# Generated by Django 2.0.1 on 2018-09-02 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BMS', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
