# Generated by Django 2.0.1 on 2018-09-02 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BMS', '0003_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
